### ISSUE TITLE
Trilha PHP - Maratona de Porto Alegre

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/Materiais-Graficos#6]
Organização e conteúdo para trilha de PHP.

cc @galvao

**Comment by galvao** [comment]
Palestra: [Tudo o que você precisa saber sobre o PHP7.](http://www.slideshare.net/ergalvao/tudo-o-que-voc-precisa-saber-sobre-o-php7) 
Palestrante: Er Galvão Abbott (Currículo no primeiro slide)

**Comment by cyz** [comment]
@galvao update feito! http://www.eventick.com.br/maratona-wmc16

**Comment by galvao** [comment]
@cyz Mantém a issue aberta pra que os palestrantes possam ir cadastrando aqui. Além disso, desculpa, tem que atualizar a descrição da palestra para o presente, já que a versão já foi lançada: "Com a chegada da major mais importante da linguagem em muito tempo, saiba o que mudou, quais são as novidades, o que quebrou, como são decididas as mudanças e principalmente onde obter mais informações!"

**Comment by galvao** [comment]
@cyz Além disso, vamos manter o nome da trilha como Backend/PHP mesmo. Melhor porque aí posso incluir uma palestra de MongoDBou Python por exemplo. Alguns dos principais palestrantes gaúchos de PHP que eu conheço vão estar no evento de Brasília.

**Comment by edpittol** [comment]
Palestra: Desenvolvendo temas WordPress
Palestrante: Eduardo Pittol

Sou formado em Ciência da Computação pela Unisinos. Desenvolvo PHP há 8 anos e a 6 criando sites integrado com WordPress. Durante anos trabalhei numa agência entregando soluções on-line para empresas. Atualmente sou CTO do Citae.vc, um banco de dados colaborativo de citações para trabalho acadêmicos.

**Comment by galvao** [comment]
@edpittol Faltou só um resumo da palestra. Pode atualizar?
@cyz: Palestra do Pittol aprovada pra trilha Backend/PHP. Em seguida deve entrar mais uma do Jackson Mafra.

**Comment by jacksonfdam** [comment]
Palestra: Logs Centralizados e Programação Orientada a Aspecto - AKA Shit Happens
Palestrante: Jackson Mafra 
Slides: http://pt.slideshare.net/jacksonfdam/tdc-2015-poa-trilha-php-shit-happens

Veremos como usar e analizar logs com Monolog, Logstash e Elasticsearch e Programação orientada a aspectos (AOP) nos permite manter implementar diferentes preocupações em isolamento.

Name: Jackson Mafra @jacksonfdam 
Company: Aggregando Group
Bio:
In summary i am a software engineer that loves to develop the back-end and loves to be an mobile Developer.

I've talked at Locaweb Meeting of Internet Professionals, Wordcamp Porto Alegre, Mobile Brazil Conference, The Developers Conference, TcheMobile, Google Dev Fest Sul, PHP Brazil Conference.

**Comment by galvao** [comment]
@cyz Palestra do @jacksonfdam também aprovada pra trilha. Faltam duas ainda, correto? Tem mais uma a caminho, vou tentar fechar a última no mais tardar amanhã

**Comment by edpittol** [comment]
Descrição da palestra:
Palestra de introdução a criação de temas para o WordPress. Vamos ver alguns conceitos básico utlilzado no desenvolvimento WordPress (template tags, hooks, customizer...).

Quanto tempo é de palestra?

**Comment by galvao** [comment]
Valeu, @edpittol!

**Comment by edpittol** [comment]
Quanto tempo é de palestra?

**Comment by cyz** [comment]
40 min

**Comment by edpittol** [comment]
+1

On Thu, Mar 3, 2016 at 3:46 PM, Cynthia Zanoni <notifications@github.com>
wrote:

> 40 min
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WoMakersCode/to-do/issues/6#issuecomment-191909626>.
>



-- 
/**

Eduardo Pittol

*/
