### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by christiano** [WoMakersCode/Materiais-Graficos#7]
Atendendo pedidos do @galvao estou enviando a proposta de palestra sobre MongoDB

Título: MongoDB - Tudo o que você precisa saber
Descrição: Uma viagem pelo MongoDB, um banco de dados orientado a documentos. Dicas de uso, boas práticas, o que fazer e o que não fazer em bancos não relacionais. Essa palestra aborda conceitos importantes e schema design. 

Curriculum do autor:
Christiano Anderson é arquiteto de dados na Propus Data Science, se especializou em persistência poliglota, trabalha com MongoDB (e outros bancos NoSQL) em diversos projetos no Brasil e exterior. 
Twitter: http://twitter.com/dump
Blog: http://christiano.me
Empresa: http://propus.science

Se precisarem de algo mais, me informe.

Abraços

**Comment by galvao** [comment]
@cyz Palestra aprovada pra trilha Backend/PHP
